///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ExcelDatadriveLoopAndCapture
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GatherArticles recording.
    /// </summary>
    [TestModule("02c5d645-aa8f-4ac3-825f-1cb450c67a3e", ModuleType.Recording, 1)]
    public partial class GatherArticles : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ExcelDatadriveLoopAndCaptureRepository repository.
        /// </summary>
        public static ExcelDatadriveLoopAndCaptureRepository repo = ExcelDatadriveLoopAndCaptureRepository.Instance;

        static GatherArticles instance = new GatherArticles();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GatherArticles()
        {
            nextcheck = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GatherArticles Instance
        {
            get { return instance; }
        }

#region Variables

        string _nextcheck;

        /// <summary>
        /// Gets or sets the value of variable nextcheck.
        /// </summary>
        [TestVariable("cfba7ffc-146b-4701-b045-6cc67209e8e8")]
        public string nextcheck
        {
            get { return _nextcheck; }
            set { _nextcheck = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            CheckForNextPageAndSetNextPresent();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", nextcheck, new RecordItemIndex(1));
            
            ListArticles(repo.EdgewordsTrainingAutomatedSoftware.PostsContainer);
            Delay.Milliseconds(0);
            
            Mouse_Click_Next(repo.EdgewordsTrainingAutomatedSoftware.NextInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsTrainingAutomatedSoftware.Next' at Center.", repo.EdgewordsTrainingAutomatedSoftware.NextInfo, new RecordItemIndex(4));
            repo.EdgewordsTrainingAutomatedSoftware.Next.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
