///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ExcelDatadriveLoopAndCapture
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("bfd23923-cf23-4e30-833a-b4880a1278df", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ExcelDatadriveLoopAndCaptureRepository repository.
        /// </summary>
        public static ExcelDatadriveLoopAndCaptureRepository repo = ExcelDatadriveLoopAndCaptureRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            search = "ranorex";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _search;

        /// <summary>
        /// Gets or sets the value of variable search.
        /// </summary>
        [TestVariable("32ed3cfb-36b6-44df-a6c3-132e32229970")]
        public string search
        {
            get { return _search; }
            set { _search = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Navigate('https://www.edgewordstraining.co.uk/') on item 'EdgewordsTrainingAutomatedSoftware'.", repo.EdgewordsTrainingAutomatedSoftware.SelfInfo, new RecordItemIndex(0));
            repo.EdgewordsTrainingAutomatedSoftware.Self.Navigate("https://www.edgewordstraining.co.uk/");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsTrainingAutomatedSoftware.MenuMain.Search' at 12;53.", repo.EdgewordsTrainingAutomatedSoftware.MenuMain.SearchInfo, new RecordItemIndex(1));
            repo.EdgewordsTrainingAutomatedSoftware.MenuMain.Search.Click("12;53");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsTrainingAutomatedSoftware.MenuMain.InputTagS' at 48;17.", repo.EdgewordsTrainingAutomatedSoftware.MenuMain.InputTagSInfo, new RecordItemIndex(2));
            repo.EdgewordsTrainingAutomatedSoftware.MenuMain.InputTagS.Click("48;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$search' with focus on 'EdgewordsTrainingAutomatedSoftware.MenuMain.InputTagS'.", repo.EdgewordsTrainingAutomatedSoftware.MenuMain.InputTagSInfo, new RecordItemIndex(3));
            repo.EdgewordsTrainingAutomatedSoftware.MenuMain.InputTagS.PressKeys(search);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgewordsTrainingAutomatedSoftware.MenuMain.Submit' at 15;17.", repo.EdgewordsTrainingAutomatedSoftware.MenuMain.SubmitInfo, new RecordItemIndex(4));
            repo.EdgewordsTrainingAutomatedSoftware.MenuMain.Submit.Click("15;17");
            Delay.Milliseconds(200);
            
            // Capture Results
            Report.Log(ReportLevel.Info, "Section", "Capture Results", new RecordItemIndex(5));
            
            CaptureArticles(repo.EdgewordsTrainingAutomatedSoftware.PostsContainer);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
